# PASSENGER REQUESTS
POST http://localhost:3000/passengers HTTP/1.1
Content-Type: application/json

{ "name": "Büşra", "location": "Bilecik" }

###
GET http://localhost:3000/passengers/6127837cabca9616f002ee10 HTTP/1.1

###
GET http://localhost:3000/passengers HTTP/1.1

###
DELETE http://localhost:3000/passengers/612622f3896dbc2a240e34af HTTP/1.1

###
PATCH  http://localhost:3000/passengers/6126276b93a73418fc462e7e HTTP/1.1
Content-Type: application/json

{ "name": "Patch Passenger to mongodb" }

# BOOKING REQUEST
###
POST http://localhost:3000/passengers/6127837cabca9616f002ee10/bookings HTTP/1.1
Content-Type: application/json

{ "driverId": "61279184cdd39520a4c04ee0", "origin": "İstanbul", "destination": "Edirne" }


# DRIVER REQUESTS
###
POST http://localhost:3000/drivers HTTP/1.1
Content-Type: application/json

{ "name": "Ziya", "location": "Adana" }

###
GET http://localhost:3000/drivers HTTP/1.1

###
GET http://localhost:3000/drivers/612634501ea9d308f07663b4 HTTP/1.1

###
PATCH  http://localhost:3000/drivers/612634501ea9d308f07663b4 HTTP/1.1
Content-Type: application/json

{ "name": "Ayhan" }

###
DELETE http://localhost:3000/drivers/61274cf3037ba12030f54321 HTTP/1.1